### ISSUE TITLE
Need some way to determine version of built plugin

### ISSUE THREAD

**Issue by nikhilv** [electric-cloud/flow-gradle-plugin#3]
For use when publishing to a maven artifact repository. We used to put the version number of the plugin in the filename for the plugin jar file. Now that we just have <projectName.jar> we must find another way to retrieve this piece of information.

Ideas:
- Restore it to the file name
- Add a gradle task to output just the version
- Encode it in the jar? java -jar <projectName.jar> outputs the version?

**Comment by bva** [comment]
Done, added task printPluginVersion to plugin.
